version: "3.9"

services:
  backend:
    build: ./devmate
    container_name: devmate-backend
    ports:
      - "8000:8000"
    volumes:
      - ./devmate:/app
    env_file:
      - ./devmate/devmate/.env
    restart: always

  frontend:
    build: ./devmate-ui
    container_name: devmate-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./devmate-ui:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./devmate-ui/.env
    restart: always
